OPENAI_API_KEY: YOUR_OPEN_API_KEY
PALM_API_KEY: YOUR_PALM_API_KEY
HUGGING_API_TOKEN: YOUR_HUGGING_FACE_API_TOKEN

DB_NAME: samocoder_main
DB_HOST: localhost
DB_USERNAME: admin
DB_PASSWORD: admin
DB_URL: postgresql://admin:admin@localhost:5432/samocoder_main

REDIS_URL: "localhost:6379"

WEAVIATE_USE_EMBEDDED: true


GOOGLE_API_KEY: YOUR_GOOGLE_API_KEY
SEARCH_ENGINE_ID: YOUR_SEARCH_ENIGNE_ID
SERP_API_KEY: YOUR_SERPER_API_KEY

# GITHUB
GITHUB_USERNAME: YOUR_GITHUB_USERNAME
GITHUB_ACCESS_TOKEN: YOUR_GITHUB_ACCESS_TOKEN

#SLACK
SLACK_BOT_TOKEN: YOUR_SLACK_BOT_TOKEN

# For running stable diffusion
STABILITY_API_KEY: YOUR_STABILITY_API_KEY

LANCE_DB_PATH: "D:/AI/SamoCoder/.lance"

## To use chroma for vector store in resources manager
#CHROMA_HOST_NAME: YOUR_CHROMA_HOST_NAME
#CHROMA_PORT: YOUR_CHROMA_PORT

## To use Qdrant for vector store
#QDRANT_HOST_NAME: YOUR_QDRANT_HOST_NAME
#QDRANT_PORT: YOUR_QDRANT_PORT