image_models:
  fireworks:
    name: fireworks
    models:
      - "accounts/fireworks/models/SSD-1B"
      - "accounts/fireworks/models/stable-diffusion-xl-1024-v1-0"
    available: true
    api_key: true
    api_key_name: FIREWORKS_API_KEY
  together:
    name: together
    models:
      - "SG161222/Realistic_Vision_V3.0_VAE"
      - "prompthero/openjourney"
      - "stabilityai/stable-diffusion-xl-base-1.0"
    available: true
    api_key: true
    api_key_name: TOGETHER_API_KEY
